[build]
  command = "npm install && NODE_ENV=production npx next build && ls -la && ls -la .next || true"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Görüntü dönüşüm ayarları kaldırıldı, çünkü Next.js'in kendi görüntü optimizasyonu kullanılıyor 