[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps --production=false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ] 