[build]
  command = "npm install && NODE_ENV=production npx next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  IYZICO_API_KEY = "sandbox-afXhZPW0MQlE4dCUUlHcEopnMUhOPTR3"
  IYZICO_SECRET_KEY = "sandbox-wbwpzKIiplZxI3hh5ALI4EXaVtSjwPxK"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Görüntü dönüşüm ayarları kaldırıldı, çünkü Next.js'in kendi görüntü optimizasyonu kullanılıyor 