[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--no-warnings"
  NEXT_IGNORE_TYPE_ERROR = "true"
  CI = "false"
  SKIP_TYPE_CHECK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[images]
  remote_images = [
    "https://ext.same-assets.com/**"
  ]

[plugins.inputs]
  staticExport = true 